site_name: Diary56x
theme:
  name: material
  language: en
  logo: images/logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/diary56x
    - icon: fontawesome/brands/github
      link: https://github.com/AlanTheKnight/diary56x
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - tables

repo_url: https://github.com/AlanTheKnight/diary56x
site_author: Maxim Gusev
dev_addr: "127.0.0.1:3000"
