# Generated by Django 3.2.15 on 2023-06-24 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Свободен'), (2, 'В работе'), (3, 'Дома')], default=1)),
                ('delivery_man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('geotag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Открыт'), (2, 'Готовится'), (3, 'В пути'), (4, 'Закрыт')], default=1)),
                ('order_list', models.JSONField()),
                ('comments', models.TextField()),
                ('end_point', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_time', models.DateTimeField()),
                ('actual_delivery_time', models.DateTimeField()),
                ('start_cook_time', models.DateTimeField()),
                ('end_cook_time', models.DateTimeField()),
                ('start_delivery_time', models.DateTimeField()),
                ('end_delivery_time', models.DateTimeField()),
                ('delivery_man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deliveryman')),
                ('kitchen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kitchen')),
            ],
        ),
    ]
