# Generated by Django 3.2.19 on 2023-06-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Свободен'), (2, 'Доставляет'), (3, 'Не на смене')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geotag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Открыт'), (2, 'Готовится'), (4, 'В пути'), (5, 'Закрыт'), (3, 'Ждет курьера')], default=1)),
                ('order_list', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('delivery_comments', models.TextField(blank=True, null=True)),
                ('end_point', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expected_time', models.DateTimeField(blank=True, null=True)),
                ('end_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('start_cook_time', models.DateTimeField(blank=True, null=True)),
                ('end_cook_time', models.DateTimeField(blank=True, null=True)),
                ('start_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('number_in_queue', models.IntegerField(blank=True, null=True)),
                ('delivery_man_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deliveryman')),
                ('kitchen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kitchen')),
            ],
        ),
    ]
