# Generated by Django 3.2.19 on 2023-06-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230625_1716'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='geotag',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_man_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.deliveryman'),
        ),
        migrations.DeleteModel(
            name='DeliveryMan',
        ),
    ]
