# Generated by Django 3.2.15 on 2023-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(default=None, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(verbose_name='Telegram ID'),
        ),
    ]
